Organisation Details :
{
  Business_Name = "Samsung SDSA";
  Business_Address = "7100 Metropolis Dr";
  Contact_Name = "Data Center Operations";
  Contact_Phone = "N/A";
  Op_Tech_Name = "t.schenk@samsung.com";
};
PDF_Certificate :
{
  PDF_Enable = "ENABLED";
  PDF_Preview = "DISABLED";
};
Selected Customer :
{
  Customer_Name = "Samsung SARC/ACL";
  Customer_Address = "3900 N Capital of Texas Hwy, Austin, TX 78746";
  Contact_Name = "Compute Team";
  Contact_Phone = "512-425-2500";
};
